DOWNLOAD_VERSION: 0.8.2

langs:
  de: Deutsch
  fr: Français
  en: English
  ja: 日本語
  nl: Nederlands
  
section:
  index:
    de: 
    en: 
    fr: 
    ja: 
    nl: 
  about:
    de: ueber
    en: about
    fr: a-propos
    ja: about
    nl: over
  fund:
    de: kapital
    en: fund
    fr: fonds
    nl: fonds
  getting-started:
    de: erste-schritte
    en: getting-started
    fr: bitcoin-debuter
    ja: getting-started
    nl: aan-de-slag
  materials:
    de: materialien
    en: materials
    fr: materiel
    nl: bronnen
  merchant-tools:
    de: verkaeufer-werkzeuge
    en: merchant-tools
    fr: bitcoin-commerce
    ja: merchant
    nl: voor-handelaars
  mining-guide:
    de: mining-anleitung
    en: mining-guide
    fr: guide-minage
    nl: ontginnings-gids
  questions:
    de: questions
    en: questions
    fr: questions
    nl: vragen
  team:
    en: team
    fr: equipe
    nl: team
  translations:
    de: uebersetzungen
    en: translations
    fr: traductions
    nl: vertalingen
